#!/bin/sh

function usage() {
    echo "Build script"
    echo ""
    echo "./build"
    echo "\t-h --help"
    echo "\t-w --watch"
    //echo "\t--environment=$ENVIRONMENT"
    echo ""
}

function buildNoWatch {
  echo "Building..."
  sass --style compact style.scss:style.css
  echo "Success!"
}

function buildWatch() {
  sass --watch --style compact style.scss:style.css
}

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
        -w | --watch)
            buildWatch
            exit
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

if [ "$1" == "" ]; then
  buildNoWatch
fi
